### ISSUE TITLE
Рок-календарь

### ISSUE THREAD

**Issue by ogursan** [EQ-Port/site#10]
Календарь должен представлять собой виджет, в котором будет написано что-то вроде "Сегодня <какое-то там число>, в этот день <сколько-то там лет назад> группа "Морковки" выпустила свой дебютный сингл". В идеале нужно, чтобы фразы варьировались. Хранить всю информацию по календарю нужно в базе.
id
date - дата (без времени)
description - описание события

**Comment by kmzsl** [comment]
Добавил в проект рок-календарь, вызвать его на нужной странице можно так:

$this->widget('application.extensions.rockcalendar.rockcalendar');

Работает так: берет текущею дату, смотрит по этой дате в базе на наличие записей, если есть то выводит их. Так же смотрит на разницу во времени с текущей датой и датой события и выводит эту разницу к примеру "2 года", "5 лет", "4 года". если разницы нет то выводит просто дату и описание события. выводится все пока print`ом. как будет верстка тогда натяну на календарь.
