### ISSUE TITLE
Мероприятия

### ISSUE THREAD

**Issue by ogursan** [EQ-Port/site#8]
Создать таблицу для хранения мероприятий.
id
name - название
code - URL-код
type - тип мероприятия
description - описание
start_date - дата начала
end_date - дата окончания (может быть NULL)
place - место проведения (название объекта)
address - адрес

Создать класс Event на базе ActiveRecord. Создать контроллер, адрес мероприятия должен быть таким /event/url-code/
Тип записывать целым числом. Для типов завести константы в классе Event

**Comment by ogursan** [comment]
код должен быть читаемым. в идеале делать транслит названия

**Comment by kmzsl** [comment]
Добавил константы, добавил транслитерацию url, теперь урл такого вида /event/Тестовое мероприятие для проверки/, становится таким /event/Testovoe_meropriyatie_dlya_proverki/ . единственное что пока не сделано это вывод ошибки о том что нет записей по данному url_code вместо этого идет редирект на главную.
